2024-09-13 16:44:17,547 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:44:17,644 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 16:44:23,099 INFO: 用户 user07 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:84]
2024-09-13 16:44:23,101 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:87]
2024-09-13 16:44:23,140 INFO: 用户 user07 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:106]
2024-09-13 16:44:28,993 INFO: 登录尝试 - 用户名: user07, IP: 127.0.0.1, 主机: 127.0.0.1:5000, 经度: 106.55266582275418, 纬度: 29.742933291032504, 位置: 重庆市 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:38]
2024-09-13 16:44:29,152 INFO: 用户 user07 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:50]
2024-09-13 16:44:29,376 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 16:45:31,212 INFO: 聊天记录已被清除 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:94]
2024-09-13 16:47:22,212 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:47:22,406 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 16:47:32,607 INFO: 用户 user07 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:67]
2024-09-13 16:47:32,608 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:47:32,636 INFO: 用户 user07 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:106]
2024-09-13 16:47:36,959 INFO: 登录尝试 - 用户名: user07, IP: 127.0.0.1, 主机: 127.0.0.1:5000, 经度: 106.552666, 纬度: 29.742932949944155, 位置: 重庆市 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:38]
2024-09-13 16:47:37,120 INFO: 用户 user07 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:50]
2024-09-13 16:47:37,301 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 16:53:01,605 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:53:01,901 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:53:05,722 INFO: 用户 user07 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:53:05,722 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:53:05,754 INFO: 用户 user07 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:106]
2024-09-13 16:53:10,857 INFO: 登录尝试 - 用户名: user07, IP: 127.0.0.1, 主机: 127.0.0.1:5000, 经度: 106.55266584641434, 纬度: 29.742933073886398, 位置: 重庆市 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:38]
2024-09-13 16:53:11,016 INFO: 用户 user07 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:50]
2024-09-13 16:53:11,199 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:56:37,690 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:56:37,906 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:56:40,849 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:56:40,850 INFO: 用户 user07 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:56:40,851 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:56:40,874 INFO: 用户 user07 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:106]
2024-09-13 16:56:45,663 INFO: 登录尝试 - 用户名: user07, IP: 127.0.0.1, 主机: 127.0.0.1:5000, 经度: 106.55266600000002, 纬度: 29.742932843507905, 位置: 重庆市 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:38]
2024-09-13 16:56:45,805 INFO: 用户 user07 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:50]
2024-09-13 16:56:45,991 INFO: 用户 user07 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:57:01,150 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:57:01,150 INFO: 用户 user07 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:57:01,151 INFO: 用户 user07 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:57:01,182 INFO: 用户 user07 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:106]
2024-09-13 16:57:06,249 ERROR: Exception on /register [POST] [in E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py", line 72, in register
    city = get_city_from_ip(ip)
           ^^^^^^^^^^^^^^^^
NameError: name 'get_city_from_ip' is not defined
2024-09-13 16:58:22,002 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:58:29,224 ERROR: Exception on /register [POST] [in E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py", line 78, in register
    new_user = User(username=username, ip=ip, city=city)
                                          ^^
NameError: name 'ip' is not defined
2024-09-13 16:59:02,308 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 16:59:16,663 INFO: 用户 user09 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:59:20,453 INFO: 用户 user09 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:59:20,453 INFO: 用户 user09 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:59:20,455 INFO: 用户 user09 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:59:20,486 INFO: 用户 user09 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:107]
2024-09-13 16:59:29,565 INFO: 用户 user10 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:36]
2024-09-13 16:59:33,832 INFO: 用户 user10 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:59:33,833 INFO: 用户 user10 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:70]
2024-09-13 16:59:33,834 INFO: 用户 user10 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:73]
2024-09-13 16:59:33,860 INFO: 用户 user10 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:107]
2024-09-13 18:39:37,067 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 18:39:44,871 INFO: 登录尝试 - 用户名: user01, IP: 127.0.0.1, 主机: 127.0.0.1:5000, 经度: , 纬度: , 位置:  [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:38]
2024-09-13 18:39:45,022 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:50]
