2024-09-13 15:10:44,768 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:10:47,110 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:25]
2024-09-13 15:10:47,480 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:11:03,930 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:11:04,125 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:11:05,852 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:11:05,853 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:11:05,871 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:11:08,153 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:25]
2024-09-13 15:11:08,333 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:12:19,755 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:12:19,888 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:12:22,289 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:12:22,290 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:12:22,534 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:12:23,692 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:12:23,692 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:12:23,711 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:12:25,908 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:25]
2024-09-13 15:12:26,071 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:13:12,776 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:13:12,898 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:13:14,726 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:13:14,727 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:13:14,753 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:13:16,842 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:25]
2024-09-13 15:13:17,020 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:15:57,199 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:15:57,377 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:15:59,689 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:15:59,690 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:15:59,714 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:16:01,880 INFO: 用户 user01 登录成功 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:25]
2024-09-13 15:16:02,076 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:16:08,083 INFO: 聊天记录已被清除 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:55]
2024-09-13 15:16:29,719 INFO: 用户 user02 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:16:48,334 INFO: 用户 user02 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:45]
2024-09-13 15:16:48,335 INFO: 用户 user02 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:21:11,823 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:21:12,132 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:21:19,101 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:21:19,102 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:51]
2024-09-13 15:21:19,303 INFO: 用户 user01 连接到聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:23]
2024-09-13 15:21:29,343 INFO: 用户 user01 离开聊天室 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:48]
2024-09-13 15:21:29,344 INFO: 用户 user01 断开连接 [in E:\AWork Folder-Course Resources\py\exchange_site\app\sockets.py:51]
2024-09-13 15:21:29,365 INFO: 用户 user01 退出登录 [in E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py:63]
2024-09-13 15:21:42,886 ERROR: Exception on /register [POST] [in E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py", line 49, in register
    avatar.save(f"app/static/avatars/{filename}")
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\werkzeug\datastructures\file_storage.py", line 125, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'app/static/avatars/user04.jpg'
2024-09-13 15:22:50,001 INFO: 应用启动 [in E:\AWork Folder-Course Resources\py\exchange_site\app\__init__.py:34]
2024-09-13 15:23:01,158 ERROR: Exception on /register [POST] [in E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AWork Folder-Course Resources\py\exchange_site\app\routes.py", line 49, in register
    avatar.save(f"app/static/avatars/{filename}")
  File "E:\AWork Folder-Course Resources\py\exchange_site\.venv\Lib\site-packages\werkzeug\datastructures\file_storage.py", line 125, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'app/static/avatars/user04.jpg'
